---
title: "09-meth-quant"
output: html_document
date: "2024-12-18"
---


with code 01.1

alignments done as 

```
```{bash}
# Set variables
reads_dir="../data/"
genome_folder="../data/"
output_dir="../output/01.2-bismark"
score_min="L,0,-1.0"  # Single value for score_min

# Get the list of sample files and corresponding sample names
for file in ${reads_dir}*_R1.fastp-trim.fq.gz; do
    sample_name=$(basename "$file" "_R1.fastp-trim.fq.gz")
    
    echo "Running Bismark for sample ${sample_name} with score_min ${score_min}"

    
    # Run Bismark alignment
    /home/shared/Bismark-0.24.0/bismark \
        --path_to_bowtie2 /home/shared/bowtie2-2.4.4-linux-x86_64 \
        -genome ${genome_folder} \
        -p 8 \
        -score_min ${score_min} \
        -1 ${reads_dir}${sample_name}_R1.fastp-trim.fq.gz \
        -2 ${reads_dir}${sample_name}_R2.fastp-trim.fq.gz \
        -o ${output_dir} \
        --basename ${sample_name} \
        2> "${output_dir}/${sample_name}-bismark_summary.txt"
done
```


Besides reports this produced bam files that need to be deduplicated

```{bash}
ls ../output/01.2-bismark/*bam
```


```{bash}
pwd
```


```{bash}
find ../output/01.2-bismark/*.bam | \
xargs basename -s .bam | \
xargs -I{} /home/shared/Bismark-0.24.0/bismark/deduplicate_bismark \
--bam \
--paired \
--output_dir ../output/09-meth-quant \
../output/01.2-bismark/{}.bam

```


```{bash}
find ../output/01.2-bismark/*.bam | \
xargs -n 1 basename -s .bam | \
parallel -j 8 /home/shared/Bismark-0.24.0/deduplicate_bismark \
--bam \
--paired \
--output_dir ../output/09-meth-quant \
../output/01.2-bismark/{}.bam
```

# extraction

```
${bismark_dir}/bismark_methylation_extractor \
--bedGraph \
--counts \
--comprehensive \
--merge_non_CpG \
--multicore 28 \
--buffer_size 75% \
*deduplicated.bam
```


```
find ../output/09-meth-quant/*deduplicated.bam | \
xargs -n 1 -I{} ${bismark_dir}/bismark_methylation_extractor \
--bedGraph \
--counts \
--comprehensive \
--merge_non_CpG \
--multicore 38 \
--buffer_size 75% \
--output ../output/09-meth-quant \
{}
```